import type { Locale } from "@/lib/i18n";

export function getListingDetailLabels(locale: Locale) {
  if (locale === "en") {
    return {
      sections: {
        priceCosts: "Price and costs",
        general: "General data",
        history: "Vehicle history",
        financing: "Financing",
        vehicle: "Vehicle data",
        motor: "Engine data",
        battery: "Battery and range",
        documents: "Documents",
        tires: "Tires",
        equipment: "Equipment",
        interior: "Interior",
        technical: "Technical",
        exterior: "Exterior",
        multimedia: "Multimedia / navigation",
        extra: "Other information",
      },
      fields: {
        purchasePrice: "Purchase price",
        purchasePriceEur: "Purchase price EUR",
        yearMonth: "Model year / month",
        financingDetails: "Financing",
        financeTermMonths: "Term",
        seats: "Seats",
        doors: "Doors",
        color: "Color",
        upholsteryPrimary: "Upholstery color 1",
        upholsterySecondary: "Upholstery color 2",
        curbWeightKg: "Curb weight",
        grossWeightKg: "Gross weight",
        trunkVolumeLiters: "Trunk",
        climate: "Climate control",
        roof: "Roof",
        engineDisplacementCcm: "Displacement",
        powerKw: "Power",
        powerHp: "Power",
        cylinderLayout: "Cylinder layout",
        driveType: "Drive",
        gearboxDetail: "Transmission detail",
        batteryCapacityPercent: "Current battery capacity",
        acChargerType: "AC connector type",
        fastCharging: "Fast charging",
        wltpRangeKm: "WLTP range",
        systemPowerKw: "System power",
        systemPowerHp: "System power",
        documentsType: "Document type",
        inspectionValidUntil: "Inspection valid until",
        frontTireSize: "Summer tire size",
        rearTireSize: "Rear summer tire size",
        historyInternationalEnabled: "International history report",
        historyDomesticEnabled: "Hungarian history report",
        vatDeductible: "VAT deductible",
        tradeInAvailable: "Trade-in possible",
        availableImmediately: "Available immediately",
      },
      values: {
        yes: "yes",
        no: "no",
        months: "months",
        people: "people",
        doors: "doors",
        kg: "kg",
        liter: "liter",
        ccm: "cm3",
        kw: "kW",
        hp: "HP",
        percent: "%",
        km: "km",
        carvertical:
          "Learn more about this vehicle with an international vehicle-history service.",
        totalcar: "Check the vehicle's Hungarian history with a local history service.",
        discount: "-20%",
      },
    };
  }

  return {
    sections: {
      priceCosts: "Ar, koltsegek",
      general: "Altalanos adatok",
      history: "Jarmu eloelet",
      financing: "Finanszirozas",
      vehicle: "Jarmu adatok",
      motor: "Motor adatok",
      battery: "Akkumulator es hatotav adatok",
      documents: "Okmanyok",
      tires: "Abroncs",
      equipment: "Felszereltseg",
      interior: "Belter",
      technical: "Muszaki",
      exterior: "Kulteri",
      multimedia: "Multimedia / Navigacio",
      extra: "Egyeb informacio",
    },
    fields: {
      purchasePrice: "Vetelar",
      purchasePriceEur: "Vetelar EUR",
      yearMonth: "Evjarat",
      financingDetails: "Finanszirozas",
      financeTermMonths: "Futamido",
      seats: "Szallithato szem. szama",
      doors: "Ajtok szama",
      color: "Szin",
      upholsteryPrimary: "Karpit szine (1)",
      upholsterySecondary: "Karpit szine (2)",
      curbWeightKg: "Sajat tomeg",
      grossWeightKg: "Teljes tomeg",
      trunkVolumeLiters: "Csomagtarto",
      climate: "Klima fajtaja",
      roof: "Teto",
      engineDisplacementCcm: "Hengerurtartalom",
      powerKw: "Teljesitmeny",
      powerHp: "Teljesitmeny",
      cylinderLayout: "Henger-elrendezes",
      driveType: "Hajtas",
      gearboxDetail: "Sebessegvalto",
      batteryCapacityPercent: "Jelenlegi akkukapacitas",
      acChargerType: "AC toltocsatlakozo tipusa",
      fastCharging: "Villamtoltes",
      wltpRangeKm: "WLTP hatotav",
      systemPowerKw: "Rendszer osszteljesitmeny",
      systemPowerHp: "Rendszer osszteljesitmeny",
      documentsType: "Okmanyok jellege",
      inspectionValidUntil: "Muszaki vizsga ervenyes",
      frontTireSize: "Nyari gumi meret",
      rearTireSize: "Hatso nyari gumi meret",
      historyInternationalEnabled: "Nemzetkozi eloelet-lekerdezes",
      historyDomesticEnabled: "Magyarorszagi eloelet-lekerdezes",
      vatDeductible: "AFA visszaigenyelheto",
      tradeInAvailable: "Autobeszamitas lehetseges",
      availableImmediately: "Azonnal elviheto",
    },
    values: {
      yes: "van",
      no: "nincs",
      months: "honap",
      people: "fo",
      doors: "ajto",
      kg: "kg",
      liter: "liter",
      ccm: "cm3",
      kw: "kW",
      hp: "LE",
      percent: "%",
      km: "km",
      carvertical:
        "Tudj meg minel tobbet a jarmurol a nemzetkozi auto-eloelet szolgaltatassal!",
      totalcar: "Kerdezd le a jarmu magyarorszagi eloeletet a szolgaltatas hasznalataval!",
      discount: "-20%",
    },
  };
}
